exec-once = hyprctl keyword input:kb_layout be

exec-once = /usr/lib/polkit-kde-authentication-agent-1 #for libvirt
exec-once = ~/.config/hypr/scripts/launch-hyprpolkitagent.sh
exec-once = /usr/lib/pam_kwallet_init

#exec-once = ~/.config/hypr/scripts/launch-waybar.sh
exec-once = quickshell -p ~/.config/quickshell
#exec-once = swww-daemon

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"

exec = ~/.config/hypr/scripts/launch-hyprshade.sh

exec-once = hyprpaper

exec-once = keepassxc
exec-once = kdeconnect
exec-once = nextcloud
