# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto,cm,auto

monitor = HDMI-A-1, 1920x1080@60, 0x0, 1.0
workspace = HDMI-A-1, 21

monitor = DP-2, 1920x1080@165, 1920x0, 1.0
workspace = DP-2, 11

monitor = HDMI-A-3, 1920x1080@60, 3840x0, 1.0
workspace = HDMI-A-3, 1