wallpaper {
  monitor = DP-2
  path = ~/Pictures/sd/00050-996366581.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/sd/00050-996366581.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = ~/Pictures/sd/00050-996366581.png
  fit_mode = cover
}
